// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// requester_unexported is an autogenerated mock type for the requester_unexported type
type requester_unexported struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *requester_unexported) Get() {
	_m.Called()
}

// newRequester_unexported creates a new instance of requester_unexported. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newRequester_unexported(t interface {
	mock.TestingT
	Cleanup(func())
}, expectedCalls ...*mock.Call) *requester_unexported {
	mock := &requester_unexported{}
	mock.Mock.Test(t)
	mock.ExpectedCalls = expectedCalls

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
