// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GoGenerateExample is an autogenerated mock type for the GoGenerateExample type
type GoGenerateExample struct {
	mock.Mock
}

// Foo provides a mock function with given fields: s
func (_m *GoGenerateExample) Foo(s string) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGoGenerateExample creates a new instance of GoGenerateExample. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGoGenerateExample(t interface {
	mock.TestingT
	Cleanup(func())
}, expectedCalls ...*mock.Call) *GoGenerateExample {
	mock := &GoGenerateExample{}
	mock.Mock.Test(t)
	mock.ExpectedCalls = expectedCalls

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
